server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:productsdb
    driverClassName: org.h2.Driver
    username: valentino
    password: escorpion
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true